spring:
  application:
    name: funds-platform
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/btg_funds}
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    # Para Gmail usa una app password en SMTP_PASSWORD.
    # Para Mailtrap reemplaza SMTP_HOST, SMTP_PORT, SMTP_USERNAME y SMTP_PASSWORD.

app:
  jwt:
    secret: ${JWT_SECRET:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
